---

filebeat.prospectors:
- input_type: log
  paths:
    - ./logs/*.log

## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5043"]
